name: Python Script Workflow

on:
  workflow_dispatch: # enables manual trigger
  schedule:
    - cron: "0 4 * * *" # daily at 4AM

env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{secrets.PASSWORD }}

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Python script
        run: python main.py
